version: '3.7'
networks:
  app_network:
    driver: bridge
services:
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION:-5.0.5}
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis:/data
    networks:
      - app_network
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '127.0.0.1:5532:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  postgres:
  redis: