import { Injectable } from '@nestjs/common';
import { CommandBus } from '@nestjs/cqrs';
import { CronExpression } from '@nestjs/schedule';
import { logger } from '../../../../helpers/application.helper';
import { getCacheTime } from '../../../../helpers/cache.helper';
import { ConditionalCron } from '../../../../helpers/cron.helper';
import { RedisService } from '../../../../infrastructure/redis/redis.service';
import { CommandProps } from '../../../../libs/ddd/domain/base-classes/command.base';
import { DeletePdfFilesCommand } from '../../commands/delete-pdf-files/delete-pdf-files.command';
const cryptoRandomString = require('crypto-random-string');
;
import Redlock = require('redlock');

/**
 * Class for handling the deletion of PDF files at root generated by the system (e.g. meal ticket commands).
 */
const taskName = 'delete-pdf-files' ;

@Injectable()
export class DeletePdfFilesTaskHandler {
  constructor(
    readonly redis: RedisService,
    readonly commandBus: CommandBus,
  ) {}

  @ConditionalCron(CronExpression.EVERY_DAY_AT_1AM, {
    name: taskName,
  })
  async handlePdfToDelete() {
    const now = new Date().toISOString()
    logger.info(`[${this.constructor.name}]: Start task at time ${now}`)
    let redlock: Redlock.Lock | undefined

    try {
      redlock = await this.redis.redlock.lock(
        `lock:[${this.constructor.name}]:${taskName}`,
        getCacheTime(9.5, true),
      )

      logger.info(`[${this.constructor.name}]: Start task ${taskName} at time ${now}`)
      
      const input : CommandProps<DeletePdfFilesCommand> = {
        correlationId: cryptoRandomString({ length: 8 }),
      };
      const command = new DeletePdfFilesCommand(input);

      await this.commandBus.execute(command);

      logger.info(`[${this.constructor.name}]: Task completed successfully`)

    } catch (e) {
      if (e instanceof Redlock.LockError) return
      logger.error(`[${this.constructor.name}]: Could not complete task`, e)
      throw e
    } finally {
      if (redlock) {
        await this.redis.redlock.unlock(redlock)
      }
    }
  }
}
